# Diretório onde o Chroma vai salvar os dados
persist_directory: ./chroma

# Porta da API
server:
  host: 0.0.0.0
  port: 8000

# Permitir requisições do frontend
cors_allow_origins:
  - "http://localhost:5173"

# Outras configurações opcionais
telemetry: false
